### ISSUE TITLE
XNAT target ping problem

### ISSUE THREAD

**Issue by faaronts** [mercure-imaging/mercure#60] opened 2023-10-31 09:00 UTC
**Describe the bug**
After the merge from #54 , some small commits were done. One of them (commit [2f6f1de](https://github.com/mercure-imaging/mercure/commit/2f6f1de37b1577cf3d360e0015e0905c42bc88cd)) changed the code to test if ping is OK. Before this change, if connection to XNAT was successful, ping was OK but after this commit, even though ping is OK, test is not passed and ping appears as None.

I just checked in a jupyter notebook your version and my current version to understand what may be happening since on my side ping is not working.

From your version, I got:

```console
c:\Users\FAaro\Documents\GitHub\AH-1\src\dicom-orchestrator\tests\test_pyxnat.ipynb Cell 6 line 8
      5 ping_ok = False
      7 if target.host:
----> 8     ping_result, *_ = await async_run(f"ping -w 1 -c 1 {target.host}")
      9     if ping_result == 0:
     10         ping_ok = True

c:\Users\FAaro\Documents\GitHub\AH-1\src\dicom-orchestrator\tests\test_pyxnat.ipynb Cell 6 line 4
      2 async def async_run(cmd, **params) -> Tuple[Optional[int], bytes, bytes]:
      3     """Executes the given command in a way compatible with ayncio."""
----> 4     proc = await asyncio.create_subprocess_shell(
      5         cmd, stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE, **params
      6     )
      8     stdout, stderr = await proc.communicate()
      9     return proc.returncode, stdout, stderr

File C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\subprocess.py:205, in create_subprocess_shell(cmd, stdin, stdout, stderr, limit, **kwds)
    202 loop = events.get_running_loop()
    203 protocol_factory = lambda: SubprocessStreamProtocol(limit=limit,
    204                                                     loop=loop)
--> 205 transport, protocol = await loop.subprocess_shell(
    206     protocol_factory,
    207     cmd, stdin=stdin, stdout=stdout,
    208     stderr=stderr, **kwds)
    209 return Process(transport, protocol, loop)

File C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py:1648, in BaseEventLoop.subprocess_shell(self, protocol_factory, cmd, stdin, stdout, stderr, universal_newlines, shell, bufsize, encoding, errors, text, **kwargs)
   1646     debug_log = 'run shell command %r' % cmd
   1647     self._log_subprocess(debug_log, stdin, stdout, stderr)
-> 1648 transport = await self._make_subprocess_transport(
   1649     protocol, cmd, True, stdin, stdout, stderr, bufsize, **kwargs)
   1650 if self._debug and debug_log is not None:
   1651     logger.info('%s: %r', debug_log, transport)

File C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py:498, in BaseEventLoop._make_subprocess_transport(self, protocol, args, shell, stdin, stdout, stderr, bufsize, extra, **kwargs)
    494 async def _make_subprocess_transport(self, protocol, args, shell,
    495                                      stdin, stdout, stderr, bufsize,
    496                                      extra=None, **kwargs):
    497     """Create subprocess transport."""
--> 498     raise NotImplementedError
```

However, in my implementation I indeed have a way to check correct ping by checking the status of the response connecting to the XNAT target host.

This is what I got:

`{'ping': True, 'loggedin': True, 'err': ''}`

by running my `test_connection` function:

```python
async def test_connection(self, target: XnatTarget) -> str:
        url = f"{target.host}/data/auth"

        async with aiohttp.ClientSession() as session:
            ping_ok = False
            try:            
                async with session.get(url, auth=aiohttp.BasicAuth(target.user, target.password)) as resp:
                    ping_ok = resp.status != 404
                    response_ok = resp.status == 200
                    text = await resp.text() if not response_ok else ""
                    return dict(ping=ping_ok, loggedin=response_ok, err=text)

            except Exception as e:
                return dict(ping=ping_ok, loggedin=False, err=str(e))
```

**Comment by RoyWiggins** [comment] 2023-11-08 13:46
I'm not sure. The error you're getting in Jupyter is coming from deep
inside asyncio, quite likely that's caused by your runtime environment (eg
running in Jupyter or Windows):

https://stackoverflow.com/questions/44633458/why-am-i-getting-notimplementederror-with-async-and-await-on-windows

It's probably not related to the issue you're having.

One thing is that your "ping" definition is simply different- we are doing
a literal "ping <host>" to see if the host is reachable and online,
regardless of the status of the service itself. This is mostly to make
check you've typed in the hostname of a reachable server, and to
distinguish between "this server doesn't exist or isn't reachable" and "the
service you're trying to reach is misconfigured or disabled." Your code is
doing a full HTTP request instead.

It may be that you want to have three results from a test: ping, http
status not a 404, and http status is actually 200. This makes sense since
you want to know 1) whether the xnat service is up and 2) whether your
credentials are correct.

You can return all three statuses as a dictionary and they will be passed
to this template to be displayed:

https://github.com/mercure-imaging/mercure/blob/master/webinterface/templates/targets/xnat-test.html

I'm not sure why it's not displaying properly. If "ping -w 1 -c 1 <host>"
at the command line works then it should display correctly.

**Comment by tblock79** [comment] 2023-11-14 08:56
Merged your PR into the main branch. Many thanks for your work on this!

**Closed by tblock79** 2023-11-14 08:56 UTC
